include $(CLEAR_VARS)
LOCAL_MODULE := NexusLauncher
LOCAL_SRC_FILES := $(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Home Launcher2 Launcher3
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
